services:
  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: db_auth
    volumes:
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  server:
    build: .
    environment:
      HTTP_PORT: 8080
      DB_HOST: localhost
    depends_on:
      - db
    ports:
      - 8080:8080