services:
  db:
    image: postgres
    hostname: db
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: db_auth
    ports:
      - "5432:5432"
    volumes:
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
  server:
    build: .
    environment:
      HTTP_PORT: 8080
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 12345
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

